import { ITreeItem } from "./tree-manager/shared/interfaces";
import { IconAction } from 'code-easy-components';

export const items: ITreeItem[] = [
    { id: "0", label: "Item 01", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, isDisabledClick: true, isDisabledSelect: true, isDisabledDoubleClick: true },
    { id: "1", label: "Item 02", isSelected: true, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '0', icon: IconAction, hasWarning: true, isEditing: true, isAllowedToggleNodeExpand: true, isDisabled: false },
    { id: "2", label: "Item 03", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '1', isDisabled: true },
    { id: "3", label: "Item 04", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '2' },
    { id: "4", label: "Item 05", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '3' },
    { id: "5", label: "Item 06", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '4' },
    { id: "6", label: "Item 07", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '5' },
    { id: "7", label: "Item 08", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '6' },
    { id: "8", label: "Item 09", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '7' },
    { id: "9", label: "Item 10", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '8' },
    { id: "10", label: "Item 11", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '9' },
    { id: "11", label: "Item 12", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '10' },
    { id: "12", label: "Item 13", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '11' },
    { id: "13", label: "Item 14", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '12' },
    { id: "14", label: "Item 15", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '13' },
    { id: "15", label: "Item 16", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '14' },
    { id: "16", label: "Item 17", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '15' },
    { id: "17", label: "Item 18", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '16' },
    { id: "18", label: "Item 19", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '17' },
    { id: "19", label: "Item 20", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '18' },
    { id: "20", label: "Item 21", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '19', hasWarning: true },
    { id: "21", label: "Item 22", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '20', icon: IconAction, isDisabledDrag: false, isDisabled: true },
    { id: "22", label: "Item 23", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '21', icon: IconAction, isDisabledDrag: true, isDisabledDrop: true, isDisabled: false, hasError: true },
    { id: "23", label: "Item 24", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '22', isDisabledSelect: true },
    { id: "30", label: "Item 30", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: undefined, description: 'Minha descrição de teste', isDisabledDrag: false, isDisabled: true, hasWarning: true },
    { id: "31", label: "Item 31", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '30', isDisabledDrag: true, isDisabledDrop: true, isDisabled: false, hasError: true },
];
