import { ITreeItem } from "./tree-manager/shared/interfaces";
import { IconAction } from 'code-easy-components';

export const items: ITreeItem[] = [
    { id: "0", icon: IconAction, type: 'ITEM', label: "Item 01", isSelected: false, hasWarning: false, ascendantId: undefined, nodeExpanded: false, showExpandIcon: false, canDropList: ['ITEM'], isDisabledClick: true, isDisabledSelect: true, isDisabledDoubleClick: true, useCustomIconToExpand: true },
    { id: "1", label: "Item 02", isSelected: true, isEditing: true, canDropList: ['ITEM'], type: 'ITEM', ascendantId: '0', nodeExpanded: false, isAllowedToggleNodeExpand: true, isDisabled: false, hasWarning: false },
    { id: "2", label: "Item 03", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '1', isDisabled: true, hasWarning: false },
    { id: "3", label: "Item 04", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '2', hasWarning: false },
    { id: "4", label: "Item 05", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '3', hasWarning: false },
    { id: "5", label: "Item 06", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '4', hasWarning: false },
    { id: "6", label: "Item 07", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '5', hasWarning: false },
    { id: "7", label: "Item 08", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '6', hasWarning: false },
    { id: "8", label: "Item 09", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '7', hasWarning: false },
    { id: "9", label: "Item 10", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '8', hasWarning: false },
    { id: "10", label: "Item 11", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '9', hasWarning: false },
    { id: "11", label: "Item 12", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '10', hasWarning: false },
    { id: "12", label: "Item 13", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '11', hasWarning: false },
    { id: "13", label: "Item 14", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '12', hasWarning: false },
    { id: "14", label: "Item 15", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '13', hasWarning: false },
    { id: "15", label: "Item 16", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '14', hasWarning: false },
    { id: "16", label: "Item 17", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '15', hasWarning: false },
    { id: "17", label: "Item 18", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '16', hasWarning: false },
    { id: "18", label: "Item 19", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '17', hasWarning: false },
    { id: "19", label: "Item 20", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '18', hasWarning: false },
    { id: "20", label: "Item 21", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '19', hasWarning: true },
    { id: "21", icon: IconAction, label: "Item 22", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '20', isDisabledDrag: false, isDisabled: true, hasWarning: false },
    { id: "22", icon: IconAction, label: "Item 23", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '21', isDisabledDrag: true, hasWarning: false, isDisabledDrop: true, isDisabled: false, hasError: true },
    { id: "23", type: 'ITEM', label: "Item 24", isSelected: false, hasWarning: false, nodeExpanded: false, ascendantId: '22', canDropList: ['ITEM'], isDisabledSelect: true },
    { id: "30", label: "Item 30", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: undefined, isDisabledDrag: false, isDisabled: true, hasWarning: true },
    { id: "31", label: "Item 31", isSelected: false, canDropList: ['ITEM'], type: 'ITEM', nodeExpanded: false, ascendantId: '30', isDisabledDrag: true, isDisabledDrop: true, isDisabled: false, hasError: true, hasWarning: false },
];
